### ISSUE TITLE
Fast Foward won´t work with GBA post 120FPS

### ISSUE THREAD

**Issue by Flaitt11** [351ELEC/351ELEC#133]
Hi! Not a programmer here, just a user in search of help.

I am trying to use fast foward in gba emulators but with no sucess. 

Searched the whole internet for a fix and tried everything it threw at me with no results. No matter what i do, game speed does not change. It works fine with other emulators like GBC for example.

Not sure if it is a bug or the problem is the little piece behing the machine (me). Hope someone can help.

Just for information, i can get it to top 120fps, but no matter what i do, it wont go over that, even with FF at 0x or 10x

Thank you!

**Comment by fewtarius** [comment]
Please use discord for support.
