### ISSUE TITLE
gzdoom

### ISSUE THREAD

**Issue by fabinhojcr** [351ELEC/351ELEC#134]
today i came across the mod Castlevania: Simon's Destiny for Gzdoom and it's a great Doom mod, is it possible to add Gzdoom to 351ELEC and play this mod?

**Comment by fewtarius** [comment]
As I've previously mentioned, we require use of templates for bug reports and feature requests, and discord for support.

**Comment by fabinhojcr** [comment]
I don't use discord and I didn't make any requests, I just asked the question if it is possible to use gzdoom on the system.

**Comment by XargonWan** [comment]
FYI: I am trying to port lzdoom but I don't think that that mod can work on lz. 
Gz instead needs opengl that is not supported. 
But we may continue this discussion on Discord.

**Comment by fabinhojcr** [comment]
@XargonWan From what it seems to me, gzdoom would also be too heavy to run on rg351p.
