### ISSUE TITLE
Brightness setting not persistent through reboot/shutdown

### ISSUE THREAD

**Issue by luminose** [351ELEC/351ELEC#135]
### Describe the bug
Brightness setting defaults to 100%. Changing the setting and rebooting resets the brightness back to 100%

### To Reproduce
1. Go to Main Menu, System Settings
2. Change brightness to anything other than 100%
3. Click Back, Quit, Reboot
4. Brightness is now back to 100%

### Expected behavior
Updated brightness value should persist after reboot. 

### Device (please complete the following information):
 - v1.0.10
 - New install. Full image flashed over a previous ArkOS install using Win32DiskImager

**Comment by fewtarius** [comment]
Shut the device completely off, power it back on holding the power button for a few seconds.  Test the brightness.  Be sure not to set the brightness in RetroArch.

**Comment by luminose** [comment]
Thanks! I’m not sure what I was doing wrong.

**Comment by fewtarius** [comment]
That corrected it?  There seems to be something weird with the newer models hardware that causes brightness to not work now and then.

**Comment by luminose** [comment]
Yeah. Not sure what I did differently from before though. I was doing shutdown and reboot through the system menu.

**Comment by fewtarius** [comment]
It probably wasn't you, this hardware has some bugs.
