### ISSUE TITLE
When opening Vic-20 ROMs from EmulationStation, games do not open and you are instead taken to a CBM Basic code input screen.

### ISSUE THREAD

**Issue by zephonate** [351ELEC/351ELEC#141]
### Describe the bug
When opening a Vic-20 ROM from EmulationStation (have only tested with zipped .06 and .a0 formatted ROMs), games do not open and you are instead taken to a CBM Basic code input screen. Not sure if there's an on-screen keyboard command necessary to proceed, but nothing I've tried allows me to progress to the actual game(s),

### To Reproduce
1. Add Vic-20 ROMs to EmulationStation via the vic20 folder on the GAMES partition. ROMs I have tested are zipped .06 or .a0 format.
2. Open a game.
3. Be taken to the CBM Basic code input screen.
4. See error. Wait, try various inputs, be unable to proceed.

### Expected behavior
See above.

According to **acridAxid** on Discord, this tutorial fixes the issue on RetroPie: https://retropie.org.uk/forum/topic/26186/tutorial-how-to-load-vic-20-cartridges-straight-from-emulationstation. He believes the fix can be migrated over to 351Elec.

### Screenshots
[https://media.discordapp.net/attachments/795710612763836447/806757238681108480/image0.jpg?width=781&height=586](url)

### Device (please complete the following information):
 - 351ELEC 1.0.10

**Comment by fewtarius** [comment]
The VIC-20 emulator does not support zipped games.
