### ISSUE TITLE
AM2R port and Spelunky Clasic Port.

### ISSUE THREAD

**Issue by Albinoinverso** [351ELEC/351ELEC#147]
Friends, i'm know that both games are in another consoles like RP2 and both are Open source archives, please make this possible! Thanks in advance and thanks for the great work you are doing.

**Comment by szalik-rg351** [comment]
Thank you for letting us know about this. However I advise you to join our discord and drop this kind of suggestions here: https://discord.gg/bmXtCt88Tz
