### ISSUE TITLE
ScummVM Virtual Keyboard

### ISSUE THREAD

**Issue by mudHOAX** [351ELEC/351ELEC#160]
ScummVM should be built with the **--enable-vkeybd** flag enabling options for the virtual keyboard
https://wiki.scummvm.org/index.php/Virtual_Keyboard#:~:text=By%20default%20the%20virtual%20keyboard,when%20running%20the%20configure%20script.

At present, it is impossible to progress with certain games, such as Leisure Suit Larry 7 without connecting an external keyboard.
It would be great if we could have native support for the virtual keyboard.

I have noticed that \gamedata\scummvm\extra contains the keyboard packs; however the keymapping options are unavailable within ScummVM, so this may have simply been missed at some point?

**Comment by fewtarius** [comment]
Verified that the flag was enabled, it will be in the 2.0 nightly build tonight.
