### ISSUE TITLE
RetroArch's copy doesn't work.

### ISSUE THREAD

**Issue by PolywickStudio** [351ELEC/351ELEC#162]
### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Describe the bug
RetroArch's Extract and Copy feature doesn't work.

### To Reproduce
1. Latest 2.0 351Elec.
2. Go to RetroArch
3. Select Online Updater
4. Content Downloader
5. Select Atari/Mame/DOS/Etc...
6. Download...

### Expected behavior
1. Data should be copied to correct folders.
2. Right now it's stuck there in /download/ folder and so content doesn't get copied to correct folders.

### Device (please complete the following information):
 - Version 2.0 aa6c0be

**Comment by SmirksAlot351** [comment]
Thank you for reporting problems and making recommendations for our latest builds. However, Issues on GitHub are for stable releases only. Please use discord to report issues in our nightly builds so they can be discussed. 

https://github.com/351ELEC/351ELEC/wiki/Contributing-to-351ELEC#reporting-bugs
