### ISSUE TITLE
WiFi on 351M - can you show full error message?

### ISSUE THREAD

**Issue by PolywickStudio** [351ELEC/351ELEC#163]
### Getting started
1. The WiFi in the RG351M is flakey. It also lags out or drops repeatedly in the embedded RG351M.

### Describe the bug
When you click 'Enable WiFi', it doesn't show an error message other than, "Cannot enable wifi !"

### To Reproduce
1. Go to Network Settings
2. Go to Enable Wifi
3. After a while a message pops up "Cannot enable wifi !".

### Expected behavior
There is a return code from the code here:
https://github.com/351ELEC/351ELEC/blob/a85dc391bbba7d4d83052ff8e608ede13d6982f8/packages/ui/351elec-emulationstation/config/scripts/wifi.sh
Can you change it to:
echo "Cannot connect to WiFi. Error message is: $command.

### Device (please complete the following information):
Version 2.0 aa6c0be

### Additional context
WiFi is very flakey in RG351M.

**Comment by SmirksAlot351** [comment]
Thank you for reporting problems and making recommendations for our latest builds. However, Issues on GitHub are for stable releases only. Please use discord to report issues in our nightly builds so they can be discussed. 

https://github.com/351ELEC/351ELEC/wiki/Contributing-to-351ELEC#reporting-bugs
