### ISSUE TITLE
Cheats should be in /games/database/cht/ not /tmp/database/cht

### ISSUE THREAD

**Issue by PolywickStudio** [351ELEC/351ELEC#165]
### Getting started
I have no idea how to get cheats working for all emulators, despite putting Mame and other cheats in /tmp/database/cht/. Either it's related to the issue https://github.com/351ELEC/351ELEC/issues/162. or something else.

### Describe the bug
1. Mame and other emulators do not detect /tmp/database/cht.

### To Reproduce
1. Start Mame, any game.
2. Go to cheats after downloading
3. Doesn't work.

### Expected behavior
1. Start Mame, any game.
2. Cheats should work.

### Device (please complete the following information):
 - RG351M, Version 2.0 aa6c0be

**Comment by SmirksAlot351** [comment]
Thank you for reporting problems and making recommendations for our latest builds. However, Issues on GitHub are for stable releases only. Please use discord to report issues in our nightly builds so they can be discussed. 

https://github.com/351ELEC/351ELEC/wiki/Contributing-to-351ELEC#reporting-bugs
