### ISSUE TITLE
Should you increase partition size to 4GB or move /tmp/downloads/ to /games/download/?

### ISSUE THREAD

**Issue by PolywickStudio** [351ELEC/351ELEC#166]
### Getting started
On big downloads, 351Elec seems to bug-out or downright crash.

### Describe the bug
1. Download SNES bevels. It crashes at around 300MB. This is because the partition is 2GB with only 300mb spare. When downloading large files, it just crashes instead.

### To Reproduce
1. As an example. go to Update and Download
2. Go to The Bezels Package
3. Select SNES. It will download a huge ZIP file.
4. 351Elec freezes or crashes soon after.
5. No space on Main Partition.

### Expected behavior
1. I'm not sure? Either increase partition size or move the /downloads/ folder to /games/download or somewhere else.

### Device (please complete the following information):
- RG351M, Version 2.0 aa6c0be

**Comment by SmirksAlot351** [comment]
Thank you for reporting problems and making recommendations for our latest builds. However, Issues on GitHub are for stable releases only. Please use discord to report issues in our nightly builds so they can be discussed. 

https://github.com/351ELEC/351ELEC/wiki/Contributing-to-351ELEC#reporting-bugs
