### ISSUE TITLE
Atari Jaguar games not showing

### ISSUE THREAD

**Issue by PGD44FOR3** [351ELEC/351ELEC#168]
### Getting started
I am using an RG351P with 351elec version 1.0.11
### Describe the bug
My Atari Jaguar folder and roms are not showing

### To Reproduce
1. Rebooted
2. Recopied roms to atarijaguar folder
3. downloaded multiple bios files
4. Not showing

### Expected behavior
I put Atari Lynx roms in the correct directory and they showed fine. Atari Jaguar roms dont show

### Device (please complete the following information):
 - Version of 351ELEC is 1.0.11

**Comment by PGD44FOR3** [comment]
Was hoping to try a few Jaguar roms, any ideas of what the poblem could be?

**Comment by SmirksAlot351** [comment]
Jaguar is not a supported system as shown on our wiki.

https://github.com/351ELEC/351ELEC/wiki/Supported-Emulators-and-Ports#what-doesnt-run

**Comment by PGD44FOR3** [comment]
Sorry. Missed it. 
Thank you
