### ISSUE TITLE
Low screen brightness on RG351M

### ISSUE THREAD

**Issue by runforlife** [351ELEC/351ELEC#182]
**Description:**
I just installed 351ELEC 1.0.11 on my RG351M. I noticed that the 351ELEC has less maximum brightness then the stock Emuelec 3.8 firmware. I like the bright screens but the maximum brightness of 351ELEC in not enought for me. Has anyone run into the same problem?

**Comment by szalik-rg351** [comment]
our main theme is a little bit darker, so that might give you this feeling. Try to download the emuelec theme and see if it look same for you "es-theme-solo-horizontal-arkos-ed" this one for example. On games probably you don't notice this behaviour i guess?

**Comment by SmirksAlot351** [comment]
Please feel free to join us in Discord to discuss questions such as this.

https://github.com/351ELEC/351ELEC/wiki#getting-help
