### ISSUE TITLE
Amstrad CPC emulator CrocoDS onscreen keyboard is set up as AZERTY instead of QWERTY so many letters which are necessary to press to load games won't work.

### ISSUE THREAD

**Issue by JCORR76** [351ELEC/351ELEC#193]
### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Device (please complete the following information):
 - Version of 351ELEC that you are using

**Comment by christianhaitian** [comment]
If needed, the fix to change the keyboard from French to US is available here.  https://github.com/christianhaitian/libretro-crocods/commit/997a1f4851c53eca18c17ef753e284b3420ff871

**Comment by fewtarius** [comment]
> If needed, the fix to change the keyboard from French to US is available here. [christianhaitian/libretro-crocods@997a1f4](https://github.com/christianhaitian/libretro-crocods/commit/997a1f4851c53eca18c17ef753e284b3420ff871)

Thanks Christian!

**Comment by JCORR76** [comment]
Actually I was going to ask Christian because he included the CrocoDS emulator on ArkOS and he fixed the same problem as well but then I realized this was not his firmware LOL

**Comment by christianhaitian** [comment]
No problem.  I help here with 351Elec where I can as well.  We try to help each other across the various distros.  It's a very supportive community here.

**Comment by fewtarius** [comment]
This fix should be in the next nightly build.
