### ISSUE TITLE
V1.0.11 Initialisation Error on RG351M

### ISSUE THREAD

**Issue by allenhuang-sky** [351ELEC/351ELEC#196]
### Describe the bug
Been playing Tactics Ogre on PSP, and accidentally pressed the Data Install option. Ever since then my RG351M started initialising 351ELEC oddly, and I can no longer get to the games list or EmulationStation, but instead, I'm presented lines and lines of code when I turn-on RG351M. But yet when I take the SD card into RG351P, everything loads properly. I'm wondering if the Data Install option has corrupted some kind of initialisation/boot file? But then I don't understand why everything works on RG351P, but not RG351M?

### To Reproduce
1. Start RG351M
2. Lines and lines of code appear, won't initialise properly (see image attached)
3. To fix the problem, I put the SD card into RG351P
4. 351ELEC loads as usual, and I can play games on RG351P with the same SD card

### Expected behavior
I should be able to load 351ELEC properly on RG351M. 
Previously I was able to play all games properly on RG351M.
Furthermore, when I put another SD card loaded with 351ELEC V1.0.11, it loads fine on RG351M.

### Screenshots
Have attached image

### Device (please complete the following information):
 - 351ELEC v1.0.11
 - RG351M
 
![PXL_20210221_074641205](https://user-images.githubusercontent.com/72362504/108618919-ae154000-7486-11eb-9093-a2d5bf2b243e.jpg)

**Comment by fewtarius** [comment]
It's possible that you have a hardware issue with your 351M as 1.0.11 works fine on both.  Everything is contained on the microsd so if it were an os issue it would panic both devices.
