### ISSUE TITLE
BGM not playing on RG351M

### ISSUE THREAD

**Issue by Mouvi** [351ELEC/351ELEC#202]
351Elec 2.0 (16/02/2021)
RG351M

BGMs don't seem to work 
Mp3 Midi Flac tested, none of them work
Files are detected since I get songs name on top but no sound what so ever ( other sound in the front end work fine ) 
Also tried with different themes and nothing
Tried different mp3 file size and still no sound
Volume change notifications don't appear

**Comment by fewtarius** [comment]
FLAC, OGG, etc have been tested and work correctly.  There is a regression with MP3 that we're working to resolve, but for now the alternative formats should be sufficient.
