### ISSUE TITLE
Requesting a Theme added 

### ISSUE THREAD

**Issue by beatlesdbp** [351ELEC/351ELEC#203]
Hello I am requesting that the Cygnus theme be added to the downloadable themes in 351Elec.

https://github.com/TheRobotFactory/es-theme-cygnus/blob/master/readme.md

**Comment by fewtarius** [comment]
It looks like it should be easy to add, but we can't promise it will scale correctly on this device.

**Comment by beatlesdbp** [comment]
ok awesome thanks.
David Prospect 

 

    On Wednesday, February 24, 2021, 07:59:07 AM EST, Fewtarius <notifications@github.com> wrote:  
 
 


It looks like it should be easy to add, but we can't promise it will scale correctly on this device.

**Comment by szalik-rg351** [comment]
Added to list, thanks for information : )
i have some other on the list, but this will be added if license allow it, at some point
