### ISSUE TITLE
Won't load Playstation 7z files

### ISSUE THREAD

**Issue by Timjames4858** [351ELEC/351ELEC#205]
Try to use Playstation 7z, it just shows a blank screen then goes back to menu.

**Comment by fewtarius** [comment]
7z isn't a supported extension by Libretro.

`Extensions¶

Content that can be loaded by the PCSX ReARMed core have the following file extensions:

.bin
.cue
.img
.mdf
.pbp
.toc
.cbn
.m3u
.ccd
`

https://docs.libretro.com/library/pcsx_rearmed/
