### ISSUE TITLE
Frontend music doesn’t play on RG351M and 2.0

### ISSUE THREAD

**Issue by PapaBear7856** [351ELEC/351ELEC#213]
### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Describe the bug
Frontend music doesn’t play on RG351M with version 2.0 of 351ELEC but does play correctly on 1.0.11

### Device (please complete the following information):
 - RG351M

**Comment by anthonycaccese** [comment]
We'll need a bit more info to help on this.  What format is your background music in?  If its mp3, at this time that is not supported and we have it on our backlog to look at.

**Comment by PapaBear7856** [comment]
Yes, all are mp3. Which audio formats are currently supported in 351ELEC 2.0?

BTW, thank you to all for your contributions in making awesome gaming software!

**Comment by stickfight** [comment]
Very sorry to ask but i cant find it on any of the guides or FAQ, how do start the front end music app?

**Comment by PapaBear7856** [comment]
Copy the audio files to the folder labeled BGM on the GAMES partition then once in the system there is an option to turn on frontend music under the Sound settings after pressing Start.

**Comment by stickfight** [comment]
Thank you very much

**Comment by NetFishNReel** [comment]
I am also having the same issue with the custom frontend music not playing. Using the RG351m with 351elec 2.0. All files are in mp3 as well. Made this account to let y'all  know about it and to thank you for the great work.

**Comment by figurhead71** [comment]
Converting files from MP3 to OGG in the BGM folder for now is a quick and easy workaround and what I have done to fix this issue.

**Comment by dhwz** [comment]
fixed with next update
