### ISSUE TITLE
Screen Scraper crashes the OS

### ISSUE THREAD

**Issue by cyohn55** [351ELEC/351ELEC#214]
### Getting started
Whenever I attempt to download box art/videos etc with screen scraper the download is extremely slow (1 item downloaded or less per minute)

### Describe the bug
After selecting screen scraper, toggling the other scraping options on, and starting the screen scraper downloads--the system begins downloading each item very slowly and in some instances freezes the OS. It sometimes causes a reboot automatically and other times I have to manually reboot.

### To Reproduce
1. Go to Main menu>Scrape>toggle all "Scrape (.......)" to on>enter login credentials>scrape now
2. Freezes either immediately or after a few minutes

### Expected behavior
Expected screen scraper to download the images.

### Device (please complete the following information):
 - Version 2.0 on the RG351P

### Additional context
This isn't additional context but, I was hoping I could also ask: where are the ports located? I downloaded Half-life and a bunch of Doom and Doom 2 WADs but can't seem to find them? Thank you.

**Comment by anthonycaccese** [comment]
A few questions that will help us get more context:
- Are you logged into your screenscraper.fr account when starting the scrape?
- How many games are you attempting to scrape at a time?

**Comment by cyohn55** [comment]
I was initially logged into my account (I thought) But, I just deleted a character from my password and scraped it again. This time it’s scraping faster than it was before but eventually got an 'ERROR: 401'. I just went on their website to check if my password is valid and it looks like theyre experiencing server issues. And last night I was scraping around 3-400 games at once, after reducing the consoles to 5 at a time.

**Comment by cyohn55** [comment]
![9F1AFDE5-0FBF-479B-B3EA-7C38B71B936A](https://user-images.githubusercontent.com/74442470/109392648-4e39f180-78eb-11eb-946a-ae1958e6d6cc.jpeg)
![7DDB4461-4067-49B7-B1C8-85D06EEBA02B](https://user-images.githubusercontent.com/74442470/109392649-4ed28800-78eb-11eb-83f9-3d291c334971.png)

**Comment by cyohn55** [comment]
![9FE13309-5EDC-476A-A4D8-00845B03FDBA](https://user-images.githubusercontent.com/74442470/109392655-5abe4a00-78eb-11eb-946a-f2805e38d6af.png)

**Comment by SmirksAlot351** [comment]
This appears Screenscraper server issue. Not 351ELEC.
