### ISSUE TITLE
EmulationStation, nice presentation of metadata

### ISSUE THREAD

**Issue by qvistenanimation** [351ELEC/351ELEC#215]
Show more info about each game in EmulationStation. 

### Is your feature request related to a problem? Please describe.
If I am looking at a game there is no easy way to see all the information available for a game. I can go into editing metadata, but it won't show the free text data or let me just look at the box art etc. 
2.0 has made huge improvements in related areas, and hyperlatives sit loose with me on how much I appreciate it. Which is why I am sure there's interest to fix longstanding issues with ES. 

The default theme has "max" displaymode that shows most of it, but it still has a tiny free-text area that scrolls slowly. Changing back and forth takes a lot of presses. Also I don't think the solution should be overly theme-dependent (since other systems might have information that themes aren't prepared for). 

### Describe the solution you'd like
Expand the Y-menu to show all data, including letting you scroll the text with the right thumbstick. 

### Describe alternatives you've considered
Switch min/max mode for theme, eg with left thumbstick press and allow scrolling text with left thumbstick up and down. Select art with thumbstick left and right.

**Comment by anthonycaccese** [comment]
Good ideas but we are not looking to implement major changes to EmulationStation on our end.  We aim to remain in sync with the upstream source for ES so as major additions are made there we can roll them into 351ELEC easily (this was the source of many of the ES improvements that came in for 2.0).  That said, 351ELEC is open source and if you’d like to contribute we’d very much appreciate the contribution.
