### ISSUE TITLE
Problems adding ROMs to folders in GAMES using mac 

### ISSUE THREAD

**Issue by BEM656** [351ELEC/351ELEC#217]
Hi all,

I just downloaded 351ELEC version 2.0 I then wrote it on to a new SD card. 

I am now trying to drag a ROM to the appropriate folder in the GAMES partition. However, it will not let me drag any ROMS to any folder. When I try the mouse become a stop sign. Any ideas?

I am using macOS Catalina Version 10.15.6

**Comment by SmirksAlot351** [comment]
Please join us on discord to help with this question. This is not a bug with the baseline.
