### ISSUE TITLE
2.0 will not revognize device as a ps1 controller 

### ISSUE THREAD

**Issue by FB74** [351ELEC/351ELEC#218]
### Describe the bug
Several ps1 Games/roms starts up and works fine in 1.11 but when using 2.0 they only starts up. When the intro s are over the device is not recognized as a ps1 controller. The roms are in the right folder what I can see. Same bios as in 1.11. 
File extension problem? Shouldn't be because works fine in 1.11?

Regards 

### To Reproduce
Start a ps1 game.

**Comment by fewtarius** [comment]
The solution to configuring the various PSX controller modes can be found in the WIKI.

**Comment by FB74** [comment]
Do you really need to confiq the rg351p device as a controller?

**Comment by fewtarius** [comment]
> Do you really need to confiq the rg351p device as a controller?

https://github.com/351ELEC/351ELEC/wiki/Getting-to-Know-351ELEC#playstation-default-controls
