### ISSUE TITLE
Request for a BBC Micro emulator

### ISSUE THREAD

**Issue by SuperBadger77** [351ELEC/351ELEC#220]
Please could I request the addition of a BBC Micro emulator. It's my favourite system (along with the Acorn Electron) of all time. I lot of good memories and I bet others would appreciate it. It's available on The RA, and via Advance MESS.

A port was recently made for the RG350 which can be found here:
https://github.com/jeremyrayner/beebem-rg350 the dev made some changes to record the key input to joypad mappings saved per each game.

Original source code here: http://beebem-unix.bbcmicro.com/download.html

A bunch of git resources here: https://github.com/stardot

Original source used for the RG350: https://github.com/thefossilrecord/beebem-rs97

Would be greatly appreciated.

**Comment by stickfight** [comment]
oooh original elite!

**Comment by SuperBadger77** [comment]
Yes - in all it's glory :-) does this mean there is a chance? :-)

**Comment by SuperBadger77** [comment]
👍🏻😃

**Comment by fewtarius** [comment]
We're not going to add this one, but if someone in the community wants to contribute the package we'll gladly merge it in.

**Comment by ShamelessPolymorph** [comment]
Fascists

**Comment by SuperBadger77** [comment]
> We're not going to add this one, but if someone in the community wants to contribute the package we'll gladly merge it in.

Can you take the source code from the links above, compile it, and merge that package in?
