### ISSUE TITLE
Slow startup/boot

### ISSUE THREAD

**Issue by v0c0der** [351ELEC/351ELEC#222]
I noticed that for the last few days 351ELEC 2.0 is starting much slower than before. After the power button is pressed, it takes about a minute until the config files are loaded. Is there some way to troubleshoot this or is it expected behavior after adding some ROMs and customizing settings?

This is on a RG351M with WIFI turned off.

Other than that the systems runs perfectly. Thanks so much for this awesome project!

**Comment by fewtarius** [comment]
There's really not a lot in the way of logging during the boot except what you can find in the systemd journal.  Something is definitely wrong though, it shouldn't take more than about 20 seconds to boot which I already consider to be too long.
