### ISSUE TITLE
Allow Retroarch settings to be saved in Retroarch

### ISSUE THREAD

**Issue by zomgugoff** [351ELEC/351ELEC#226]
I am aware Retroarch settings were made available in the Emulationstation software to make things "easier", but it's a problem when trying to make and save adjustments while a game is running. Having to run a game, make and remember adjustments, then exit and make your way though several menus to make the changes in the Emulationstation menu is a slow and inconvenient process. Especially for things like shaders that you may want to change frequently.

I would like to suggest adding an option to allow Retroarch to save all of its own settings (in other words, ignore the Emulationstation settings).

**Comment by fewtarius** [comment]
This is not possible the way that 351ELEC is developed.
