### ISSUE TITLE
Taking a screenshot crashes RetroArch

### ISSUE THREAD

**Issue by BSoD38** [351ELEC/351ELEC#232]
### Describe the bug
The "Take Screenshot" feature on RetroArch crashes it. The screen become black for a while, then ends up returning to ES. I can reproduce it systematically using SNES9X.

### To Reproduce
1. Run an SNES game with default settings (I tried with the english patched version of *Kyuuyaku Megami Tensei*)
2. Open the menu
3. Click "Take Screenshot"
4. RetroArch crashes

### Expected behavior
A screenshot is taken and there is no crash.

### Device (please complete the following information):
 - RG351P with 351ELEC 2.0

**Comment by fewtarius** [comment]
This is a known issue, and something we believe may be an issue upstream.
