### ISSUE TITLE
Add option for Gamelist View Style - Wheel art

### ISSUE THREAD

**Issue by Namdor-07** [351ELEC/351ELEC#238]
Currently GAMELIST VIEW STYLE options allow for:
Automatic
Basic
Detailed
Video
Grid

I would like to propose that "Wheel art" would be available in the GAMELIST VIEW STYLE options. Instead of the basic text I would like to be able to scroll through my game list with just the wheel art that can be scraped.

Thank you for considering this.

**Comment by anthonycaccese** [comment]
This is being researched as part of the theme work located here
