### ISSUE TITLE
Unwanted behavior when deleting PS1 game

### ISSUE THREAD

**Issue by pswiss** [351ELEC/351ELEC#240]
Description: Deleted PS1 game by going to edit metadata->delete. When it kicked me back to the menu (expected) the game list only showed the game that I had just deleted (unexpected)

I suspect that this might be due to having different files associated with the game in question (.cue, .img etc)

### Device (please complete the following information):
v2.0

**Comment by fewtarius** [comment]
There's really nothing we can do for this one, you'll have to delete these manually.
