### ISSUE TITLE
Request way of jumping to random game in a game list

### ISSUE THREAD

**Issue by pswiss** [351ELEC/351ELEC#241]
### Is your feature request related to a problem? Please describe.
It can be overwhelming to have so many games to choose from

### Describe the solution you'd like
I would like to have the ability to hit a button and have the game list jump to a random game, similar to how I can jump to a random system on the console browsing menu

### Describe alternatives you've considered
The screensaver option is ok, but requires the associated games to have video files (which I never use). The process of getting to the screensaver is also more involved than just hitting a button. Further, when using the video screensaver option to jump to a game, it did not appear on my recently played list

### Additional context
Something like clicking the right thumbstick would work

**Comment by fewtarius** [comment]
Use the video screensaver, when you see a game you would like to play press start.
