### ISSUE TITLE
GBA link

### ISSUE THREAD

**Issue by Ragntard** [351ELEC/351ELEC#242]
Since this system (RG351P) really is optimized for GBA then this should be an obvious goal to look for.
Other systems have these features through retroarch via wifi so it should theoretically be possible?

**Comment by anthonycaccese** [comment]
Unfortunately GBA link cable emulation is not possible in the currently available retroarch cores.

This FAQ from libretto has more details on netplay and what is currently supported - https://docs.libretro.com/guides/netplay-faq/
