### ISSUE TITLE
DraStic 351V stylus issues

### ISSUE THREAD

**Issue by retrogamecorps** [351ELEC/351ELEC#336]
The stylus on RG351V is non-functional, and adjusting the controls settings doesn’t seem to work for me. Resetting to default controls makes the stylus work, but with reversed controls (and it breaks some other functions).  

Christian suggests using this configuration file: https://discord.com/channels/756122568410267729/824967234161999882/838075216323805204

**Comment by szalik-rg351** [comment]
it will be sorted soon, i already sended today a PR with updated package, but waiting for Cebion to accept.

thanks :)
