### ISSUE TITLE
[Solarus] Buttons mapped incorrectly or not mapped.

### ISSUE THREAD

**Issue by LeBiquet** [351ELEC/351ELEC#340]
I'm on the last version of 351ELEC .

Games load up fine and are beautiful.

In "Return of the Hylian" and "Mystery of Solarus DX", I can't move with the D-PAD. Joystick is mapped but mirrored (UP= DOWN etc.) and has insane dead zones.

**Comment by sickhate** [comment]
U can changed them within the game. I had that issue also. Press menu go to options and change keymap. Worked very well for me. Save the file and thats it

**Comment by Cebion** [comment]
This is sadly an issue on solarus that can't be fixed on our end.
They already have an issue open for it.

**Comment by anthonycaccese** [comment]
Linking solarus issue for tracking purposes: https://gitlab.com/solarus-games/solarus/-/issues/1523

Closing for now on our end as we wait for a fix upstream
