### ISSUE TITLE
Transferring/Synch savestates from RetroPie

### ISSUE THREAD

**Issue by KingChrom** [351ELEC/351ELEC#352]
I want to play with my savestates from RetroPie 4.7.12 (Raspberry 3) on the RG351V.
I tried to copy my (e.g.) zelda.gb, zelda.srm and zelda.state files in the corresponding folder, but it didn't work.
Is it possible to Transferring/Synch Savestates from RetroPie?

**Comment by dhwz** [comment]
please use our Discord channel for questions like these, this is not a support channel
