### ISSUE TITLE
Issue on Puae Core with Pinball Illusions WHD

### ISSUE THREAD

**Issue by matercir** [351ELEC/351ELEC#366]
Hello, having an issue with Puae when playing Pinball Illusions. Whenever I exit from a table to the main menu I get an error saying the game's tables directory doesn't exist and it cannot save and I get dumped to the whdload menu.

Also sometimes when I start it dumps me directly to whdload info screen directly at random.

Using latest WHDload image of pinball illusions (non cd32 version) and running 351elec 04/22 build on 351m.

I do not have this problem on other versions of retroarch on other platforms.

**Comment by anthonycaccese** [comment]
Sorry to hear you are running into this problem, unfortunately we aren't able to offer support for individual games.  Someone in our community may be able to offer help on our discord.  You can join here: https://discord.gg/bmXtCt88Tz
