### ISSUE TITLE
PSP Issue after update

### ISSUE THREAD

**Issue by jalanimal** [351ELEC/351ELEC#380]
After updating to the new version, my up and down directions on my analog have been inverted. However the left and right still work. It has worked with every Psp game I’ve tried and can’t find any control settings to fix it. Analog works normal with every other system besides Psp.

**Comment by Marxiboy** [comment]
I was not able to replicate the issue after the update. For me, the analog stick works just as it always did.

**Comment by Cebion** [comment]
Sorry, this is no support forum.

For Support please visit us on our Discord Server
https://discord.gg/bmXtCt88Tz

Only create issues if it is reproducable issue.
