### ISSUE TITLE
Amiberry 4 crashes (segfault) / RG351V 

### ISSUE THREAD

**Issue by r3mowilliams** [351ELEC/351ELEC#382]
### Bug
Amiberry crashes (segfault) upon launching.  It appears that the emulator will start, and briefly display an Amiga white/grey kickstart boot transition, before crashing and returning to ES.

### To Reproduce
Configure Amiberry as the desired emulator for Amiga in ES.  launch a supported Amiga file (.adf will do)

### Device
RG351V / 351ELEC-RG351V.aarch64-20210510

### Additional context
All required kickstart files are present, puae/uae4arm both work upon launching the same chosen Amiga file.

Amiberry will work by reverting back to v3.3 `PKG_VERSION="77f9f926e9d25b6dde666bac08e5f4b68d3f9343"` in the build

**Comment by dhwz** [comment]
has already been fixed
