### ISSUE TITLE
DevilutionX inventory graphical bug

### ISSUE THREAD

**Issue by Marxiboy** [351ELEC/351ELEC#383]
DevilutionX Diablo port has now a graphical glitch where anything you put in the right hand (shield) will be superimposed on the left hand (sword). The shield and sword will both appear in the left hand even if, to remove the shield, you have to click on the right hand.

### To Reproduce
1. Create warrior (haven't tested it with other characters)
2. Open inventory ingame.
3. Witness the bug.

### Expected behavior
Shield in right hand and sword in left hand. Not both in left hand.

###Screenshot
https://i.postimg.cc/Z5NsDH32/20210512-222323.jpg

### Device:
 - 351ELEC - 20210510 Reborn Release on 351M

**Comment by dhwz** [comment]
you should report and/or check if this is fixed in the DevilutionX repository we are not responsible for bugs in game engines
