### ISSUE TITLE
RG 351V compatibility?

### ISSUE THREAD

**Issue by mfurniss** [351ELEC/351ELEC#389]
I have the Anbernic RG 351V.

After following the directions and flashing to a new 32GB micro SD. I insert the card in the top SD slot and power on, I get a corrupted Anbernic logo for a few seconds, the device vibrates and the LED turns red. I wait longer and the LED turns green and the screen goes black. I waited about 10 minutes, nothing happens.

I tried the Discord link, but the invite is invalid.

**Comment by GibzFGC** [comment]
Hi there.

If you are trying to use a release from this project, you shouldn't be seeing an Anbernic logo at all so I don't know what instructions / file you have used. It should be a 351ELEC logo (this isn't the stock firmware)

If you're looking to join the 351ELEC Discord, the link on the Code page works or you can go to [https://discord.gg/bmXtCt88Tz](https://discord.gg/bmXtCt88Tz).
