### ISSUE TITLE
GAMES Folder missing

### ISSUE THREAD

**Issue by HansDampfTante** [351ELEC/351ELEC#402]
Hello everybody,
i own a rg351m, it arrived a few days ago and its my first retro handheld device.

I put in a new 128gb sd card and installed 351elec, no issues. I put all my roms on the sd card and everything worked for about 2 days.

today I picked up my system and it won´t boot up. So i backed up all my roms and saves on my pc and formated my sd card.

I used Rufus to flash the .img file to the sd card, and put it back in my device. 
It boots up fine. 

Now the issue: when I put it back in my PC there is no GAMES folder, only a 351ELEC folder and my SD card is reduced to 0.99GB.

where is the GAMES file gone???

thank you for your help,

HansDampf

**Comment by Cebion** [comment]
This Issue tracker is for bug reports.
Please visit our discord for technical support.
