### ISSUE TITLE
In game brightness dont works

### ISSUE THREAD

**Issue by dskmusic** [351ELEC/351ELEC#403]
## This is only for actual bugs that occur on the system! For Support visit us in our Discord
https://discord.gg/bmXtCt88Tz

### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Device (please complete the following information):
 - Version of 351ELEC that you are using

**Comment by Cebion** [comment]
Please visit our discord for device support.
This is only for reproducable bugs
