### ISSUE TITLE
Core requests

### ISSUE THREAD

**Issue by nl255** [351ELEC/351ELEC#406]
I would like to see the following cores added if it is practical to do so.  Especially SMS Plus GX.

SMS Plus GX
Mame 2000 (mame4all)
Quicknes
Mednafen supafaust
PCSX Rearmed Neon

**Comment by dhwz** [comment]
I'm currently reviewing the available cores, I'll add this one to my list.

**Comment by dhwz** [comment]
SMS Plus GX (yes)
Mame 2000 (mame4all) (for what is this one needed?)
Quicknes (doesn't work)
Mednafen supafaust (yes)
PCSX Rearmed Neon (never heard of that one?)

**Comment by nl255** [comment]
> 
> 
> SMS Plus GX (yes)
> Mame 2000 (mame4all) (for what is this one needed?)
> Quicknes (doesn't work)
> Mednafen supafaust (yes)
> PCSX Rearmed Neon (never heard of that one?)

For Mame 2000/mame4all many lower end devices use that version and it would be nice to be able to use the same romset and high score data on the 351.  As for PCSX Rearmed Neon I found the .info file in the 351elec image which I have attached as a text file.

[pcsx_rearmed_libretro_neon.txt](https://github.com/351ELEC/351ELEC/files/6525416/pcsx_rearmed_libretro_neon.txt)

**Comment by dhwz** [comment]
That's what we already have neon is the gpu of our arm processor.
