### ISSUE TITLE
Cannot start on RG351v - No Gamepads Detected

### ISSUE THREAD

**Issue by tfitzger-dev** [351ELEC/351ELEC#407]
### Describe the bug

I have been trying to flash a copy of the newest release for RG351V, and am running into an issue where it is not recognizing the gamepad.

### To Reproduce
1. Flash iso to card
2. insert microsd as internal sd card for RG351V
3. Insert microsd card as external sd card
4. turn device on
5. after device boots, see error with no gamepads

### Expected behavior
I would expect to see either ES load, or the gamepad configuration to accept inputs from the gamepad

### Screenshots

![IMG_20210517_223140868](https://user-images.githubusercontent.com/46288003/118586555-989b7380-b760-11eb-9126-a9020c2c9cdc.jpg)

### Device (please complete the following information):
Image: 351ELEC-RG351V.aarch64-20210510.img
Device: RG351V

### Additional context
Cards: Internal: 16gb PNY formatted as EXT4
           External: 128gb PNY formatted to EXT4, single partition

I have tried flashing the image using balenaEtcher, Win32DiskImager on Windows 10 and Restore Disk Image in Disks in Pop_OS!

**Comment by GibzFGC** [comment]
Hi there.

I recommend joining the Discord for tech support as it's easier to discuss things: https://discord.gg/bmXtCt88Tz
