### ISSUE TITLE
Nokia N-Gage emulator for rg351p

### ISSUE THREAD

**Issue by yeahguy72** [351ELEC/351ELEC#418]
How about a Nokia N-Gage emulator? I actually still have mine(ha-ha) for rg351p.

## This is only for actual detailed feature requests for the system! For Support or if you want to discuss ideas visit us in our Discord
https://discord.gg/bmXtCt88Tz

### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

**Comment by Cebion** [comment]
This is only for actual detailed feature requests for the system! For Support or if you want to discuss ideas visit us in our Discord
