### ISSUE TITLE
RG351V: Missing on-screen keyboard for game meta data

### ISSUE THREAD

**Issue by mtoensing** [351ELEC/351ELEC#419]
### Describe the bug
When you edit a games meta data there is no option to edit the text. This was possible in older versions of emulec. 

### To Reproduce
1. Go to game list
2. Press X
3. Edit game meta data
4. Unable to edit this text because no on screen keyboard is visible. I tried all buttons.

### Expected behavior
on screen keyboard allows to edit the text

### Screenshots
![IMG_7710](https://user-images.githubusercontent.com/136737/119253643-79fb0980-bbb2-11eb-92cf-2cb60bc22bc4.jpg)

### Device (please complete the following information):
 - 351ELEC 20210510 Reborn Release

**Comment by Cebion** [comment]
I wonder if this has ever worked on 351elec

**Comment by mtoensing** [comment]
Keyboard is missing in all menus (wifi, passwords…) had to reflash the Image. This happened after the update to reborn.

**Comment by dhwz** [comment]
invalid issue

**Comment by mderie** [comment]
Hi,
Why it is invalid ? I had the same issue with the RG351M when entering the wifi password.
I had to edit the file under Linux on my laptop...
Regards
