### ISSUE TITLE
ECWolf libretro core

### ISSUE THREAD

**Issue by masid101** [351ELEC/351ELEC#420]
Hello,

any chance of adding this core (maybe ports). I would love to play the good old Wolfenstein 3D and Spear of Destiny.

**Comment by Marxiboy** [comment]
They are already in Anberports. See https://github.com/krishenriksen/AnberPorts

**Comment by dhwz** [comment]
sure why not let me check if the core builds

**Comment by masid101** [comment]
I just tried the AnberPorts version and it doesn't work for me. I think the libretro version would be far more elegant and usable.

**Comment by tiduscrying** [comment]
I didn't do a whole lot as far as actual port work is concerned, but I did contribute it to Anberports. I don't have a 351V to test it with but I don't see any reason it wouldn't work. Have you tried using the vanilla, non Anberports release from the normal repo?

https://github.com/tiduscrying/ecwolf-rg351

**Comment by dhwz** [comment]
We don't need that anymore ecwolf is now a integrated system.

**Comment by masid101** [comment]
Thank you very much, can't wait to try out the next release and test this.
