### ISSUE TITLE
Connect to the internet but doesn´t download

### ISSUE THREAD

**Issue by victor-portella** [351ELEC/351ELEC#421]
When I connect my rg351p to the internet I got an IP adress, it says it´s connected, but when I try to download themes, packages, scrape or activate retroachievements it simply does not work. I recieve a message: "An error occurred: P.¨?!!" or something like this with random characters. I tried changing the wifi adapter and connecting to other networks but without success. Internet works well on PC.

P.S.: I´m not that experient with emulation devices. Thanks for helping.

**Comment by Cebion** [comment]
Sorry, this is no support forum.

For Support please visit us on our Discord Server
https://discord.gg/bmXtCt88Tz

Only create issues if it is reproducable issue.
