### ISSUE TITLE
Psx wont show

### ISSUE THREAD

**Issue by tufttt** [351ELEC/351ELEC#424]
Psx isn't showing on the main system menu on my rg351v and i do have it selected in the games collection settings to be displayed. I can play psx games through retroarch when i open them manually but its very inconvenient.

**Comment by dhwz** [comment]
You are missing your cue files for your bin images?
Unhide the bin extension or better create the missing cue files.

**Comment by tufttt** [comment]
Do i put the bin. File and the cue. File in a folder then put them in the psx folder or do i just put them in the psx folder separately?

**Comment by konsumschaf** [comment]
Just put everything together in the psx folder. And have a look at .chd. ;-)

**Comment by tufttt** [comment]
What do i do with games like resident evil 2 that has 2. Bin files?

**Comment by sertiana** [comment]
You can create a .m3u playlist

**Comment by tufttt** [comment]
Sorry for asking so many questions but how do i do that?

**Comment by Cebion** [comment]
Please visit our discord for support.
This is no support forum.
