### ISSUE TITLE
Can't connect via ssh, login error

### ISSUE THREAD

**Issue by dskmusic** [351ELEC/351ELEC#426]
## This is only for actual bugs that occur on the system! For Support visit us in our Discord
https://discord.gg/bmXtCt88Tz

### Describe the bug
Trying to connect via ssh give an incorrect password message, can't stablish the connection.

### To Reproduce
1. Try to connect via ssh with "root" and "351elec" user/password
2. Get error message

### Expected behavior
Correct ssh connection!

### Device (please complete the following information):
Rg351m, last reborn release

**Comment by dhwz** [comment]
Join Discord for support
