### ISSUE TITLE
Boot strait into RetroArch

### ISSUE THREAD

**Issue by Cibomatto2002** [351ELEC/351ELEC#428]
I would like to be able to boot strait into RetroArch without having to select it first.

**Comment by dhwz** [comment]
Don't misuse the issues for support.

**Comment by konsumschaf** [comment]
Either install Lakka (http://www.lakka.tv/get/linux/rg351p/) or edit the `distribution.conf` to boot into Retroarch.

**Comment by Cibomatto2002** [comment]
> Either install Lakka (http://www.lakka.tv/get/linux/rg351p/) or edit the `distribution.conf` to boot into Retroarch.

I had no idea you could edit the .conf file thanks.
