### ISSUE TITLE
At low power, system won’t boot properly 

### ISSUE THREAD

**Issue by Sjors90** [351ELEC/351ELEC#439]
I have a anbernic rg351m.
And installed 351 elec firmware.
Everything is working fine until my battery level is under 30-20%.
When I start my system with this battery level, it won’t boot properly.
I see a lot of text and numbers on my screen.
You can see it on the photo below.
But when I charge the system and push the reset button it boots up normally.
I couldn’t find any information about it.
Maybe it is a know issue, I don’t know. I just got my system this week.
I hope you have fix for this 

![E8338CAD-31E5-4098-B0B5-FBA7242913C8](https://user-images.githubusercontent.com/84965413/119963538-7f889300-bfa8-11eb-92ec-41708cddd947.jpeg)

**Comment by Cebion** [comment]
Normal behaviour on Anbernic Devices.

**Comment by Sjors90** [comment]
Ah thnx 👍🏻
