### ISSUE TITLE
Add Epic Noir theme

### ISSUE THREAD

**Issue by fry-guy** [351ELEC/351ELEC#441]
I've adapted the EmulationStation theme Epic Noir to run on 351Elec, including a number of improvements and tweaks, including slightly larger text sizes for ease of use on a handheld device and new background and controller images for systems such as the Watara Supervision and Pokemon Mini. The full theme is available at https://github.com/fry-guy/epic-noir-351elec. For a full list of the various tweaks, see the readme.

I wondered if it might be possible to add the adapted theme to the official theme repository? (I also plan to post any additional changes to the theme to the GitHub page above.

Thanks for considering.

**Comment by szalik-rg351** [comment]
Hello,
but you know that we already have it : P? 351Noir, EpicLikeSzalik, EpicCody they all have all of the controllers covered and all changes for the device ^^
