### ISSUE TITLE
Screensaver kicking in upon waking from sleep mode.

### ISSUE THREAD

**Issue by hahnlo** [351ELEC/351ELEC#451]
### Describe the bug
As titled, while this is not a major issue with other screensavers, having it set to "Sleep" makes the devices goes back to sleep the moment it wakes up.

### To Reproduce
1. Set 'Screensaver Behavior' to "Sleep"
2. Set 'Screensaver After' to 1 minute (for testing)
3. Put devices to sleep by pressing the power button.
4. Wakes the device after the set timer

### Expected behavior
Able to use the device and not having to wake it up twice.

### Screenshots
-

### Device (please complete the following information):
 351elec reborn (V20210510)

### Additional context
This can only be produced in Emustation where screensavers actually work.
This will also not occur if the device is put to sleep by the said screensaver behavior.

**Comment by pkegg** [comment]
@hahnlo - This should be fixed as part of: https://github.com/351ELEC/351ELEC/pull/540.   I will close this issue once the PR is merged.

If you would like to test this fix, you can find the PR artifacts here: https://github.com/351ELEC/351ELEC/pull/540/checks (artifacts in upper right).   For more information on installing dev/PR builds, see: https://github.com/351ELEC/351ELEC/wiki/Contributing-to-351ELEC#pull-request-builds
