### ISSUE TITLE
Brightness slider key repeat broken.

### ISSUE THREAD

**Issue by AchillesPDX** [351ELEC/351ELEC#468]
### Describe the bug
The first couple boots with the latest firmware allowed me to hold left ot right on the d-pad on the brightness control in the ES menu and the key would repeat and keep increasing or decreasing the slider. Now the key repeat is broken and I have to tap the button repeatedly to increase or decrease.

### To Reproduce
1. Install fresh OS, check brightness slider repeat.
2. Reboot system a few times.
3. Hope it breaks?

### Expected behavior
Holding left or right should cause the brightness slider to continue moving.

### Device (please complete the following information):
RG351V - 20210603

**Comment by dhwz** [comment]
This is not new and was always like that. It's a ES problem which occurs occasionally.
