### ISSUE TITLE
Dreamcast not working after Hotfix 3

### ISSUE THREAD

**Issue by fry-guy** [351ELEC/351ELEC#469]
I just installed hot fix 3 and Dreamcast simply does not work. I’ve got at 10-15 hours logged on Skies of Arcadia and now the game won't load. Tried other games, same issue. Everything worked fine before the update... very well, in fact. I tried all three core options. Something seems very wrong. Anyone know why this suddenly isn’t working?

Edit: Upon further testing, this issue seems to be affecting CDI games, not GDI games. The CDI games works previously.

Edit 2: Upon yet more testing, it seems that most but not all CDI games will not work. Notably, Gauntlet Legends will still play. All other CDI files tested so far have not worked.

**Comment by dhwz** [comment]
Please report that upstream at the libretro git then we can't fix that.

**Comment by fry-guy** [comment]
I can report upstream to libretro - but it's not just their core. I'm also encountering the problem with the other Dreamcast cores.

**Comment by dhwz** [comment]
What do you mean it's not their core? Which other cores? As have only one flycast.

**Comment by mtoensing** [comment]
Ah, this might be the same cause as this one: #465
