### ISSUE TITLE
Integrated scraping missing several systems

### ISSUE THREAD

**Issue by SuperBadger77** [351ELEC/351ELEC#473]
## This is only for actual bugs that occur on the system! For Support visit us in our Discord
https://discord.gg/bmXtCt88Tz

### Getting started
Checked issues and release notes but can't see anything about this issue.

### Describe the bug
Several of the lesser known systems are missing. I've put roms in for every system and the ones I've noticed that the user are unable to scrap for are C16, C128 and J2ME. Now I get J2ME - it's not on https://www.screenscraper.fr/ but the others are?

### To Reproduce
Add valid roms for the systems with valid extension to the c16 or c128 folders.
Start -> ES -> Scrape -> Scrape Now -> Systems
Commodore 16 and 128 not present.

### Expected behavior
Expect the user is able to scrap for all systems that are valid on the platform and are listed on screenscraper.

### Device (please complete the following information):
RG351V Crazy Hedgehog fresh install.

### Additional context
Not sure if this is an issue with the OS or Emulation Station or something else.

**Comment by dhwz** [comment]
this systems don't exist on the scraper sites thats why you can't scrape anything
