### ISSUE TITLE
Drastic emulator slow performance

### ISSUE THREAD

**Issue by AlexParkerNY** [351ELEC/351ELEC#480]
In the New version of drastic I have noticed lower performance, using the stock firmware version I could play without using frame skipping having excellent performance, but this version seems to have better resolution and that directly affects performance, in the previous version I used to disable all video options and that gave me the best performance but now it is necessary to always activate frame skipping to be able to play. I think this can be improved by going back to the previous version.

**Comment by dhwz** [comment]
We don't have a new version

**Comment by AlexParkerNY** [comment]
What could have caused that? I remember upgrading to 351 elec and after that the drastic performance decreased
