### ISSUE TITLE
PCSX-ReARMed latest update causes controller d-pad not working on RG351V

### ISSUE THREAD

**Issue by crksn36** [351ELEC/351ELEC#487]
I frequently play PCSX-ReARmed emulator with some selected psx games. the latest update 351elec 20210603 Crazy  Hedgehog hotfix for RG351V messes up dpad controller even I try remapping but doesn't work, every games I load every each doesn't work and I switch to SwanStation emulator which had a little bit laggy in sounds, graphics and movement. The previous release of 351elec 20210510 and 20210422 I had no problems with controllers. I hope can look this matter thanks!

**Comment by dhwz** [comment]
reset your device there is no issue with the controls

**Comment by crksn36** [comment]
what do you mean reset? what do I need to do? step by step?

**Comment by dhwz** [comment]
Come to Discord for support this, issues is for real issues only.

**Comment by alien2003** [comment]
> Come to Discord for support, issues is for real issues only.

Not everyone can sign up for Discord because of their draconic verification system. For example, I can't sign up at all, they ask me to verify my phone number, then ask me to verify my email and permaban me after that. Tried with multiple different phone numbers
