### ISSUE TITLE
Duckstation crash on launch

### ISSUE THREAD

**Issue by Chumara** [351ELEC/351ELEC#500]
### Describe the bug
Swanstation is fully working and updated, but the Duckstation core crashes on launch.

Launching Retroarch 32 and 64 bit doesn't show Duckstation as an option under "Load Core."

Duckstation is still shown as an option in EmulationStation.

### To Reproduce
1. Go to a PS1 game. 
2. Press select, go to advanced game options, set emulator to Duckstation. 
3. Launch the game. 

### Expected behavior
Either for Duckstation to launch correctly or for the option to be removed from EmulationStation. 

### Device (please complete the following information):
 - RG351V and RG351P both have this issue.

**Comment by dhwz** [comment]
There is no duckstation core in the current image so don't report it again
