### ISSUE TITLE
opensim hardware osh pb controller disconnected and reconnects

### ISSUE THREAD

**Issue by mwalton07** [351ELEC/351ELEC#515]
351 elec opensim hardware osh pb controller disconnected and reconnects after the crazy hedgehog update while using a TP Link TL-WN725N wifi adapter in the left otg usb c port. It disconnects and reconnects for a min then it stops and 15 to 20 Mins later it does the same disconnecting and reconnecting.

![20210625_111423](https://user-images.githubusercontent.com/58263900/123513936-f3789280-d65d-11eb-9bd8-76f0fa855a67.jpg)
![20210625_111423](https://user-images.githubusercontent.com/58263900/123513939-f96e7380-d65d-11eb-8c94-308fce2057d0.jpg)

**Comment by TheOuterLinux** [comment]
I've noticed a similar issue for when the battery drops somewhere between 30-40%.

**Comment by mwalton07** [comment]
I have tried the wifi dongle in the right OTG port and it's fine. It seems to do this in the left OTG port

**Comment by pkegg** [comment]
Unfortunately, I don't think there's much we can do here.  

The message you're seeing is tied directly to the Linux kernel (re)detection of the USB controller.  I would guess there's some kind of interference going on at a hardware level causing the detection/redection of the controller when you have the wifi card in the left port (or maybe there's a drop in electrical current, etc).

Whatever is happening, at the 351ELEC software level, we just get the messages that the controller is (re)detected.  There's not much we can do.

Given that we cannot really fix this and you have a workaround (use the right OTG port), I'm going to close this issue.  Feel free to post on discord if you are in need of further support.  Thanks for your time and responses.
