### ISSUE TITLE
LZ Doom Not saving config setting

### ISSUE THREAD

**Issue by smokeytokyo** [351ELEC/351ELEC#517]
Hi Guys,
I would like start by saying thank you guys for all the hard work that you do, we all appreciate it!

I'm not sure if someone has brought this up already, but the settings are not saving after you exit any game then reboot the device.
I'm thinking the issue is due to the Lzdoom.ini permissions being read only. I tried changing the permissions with Winscp which would provide me an Error Code 4.

I also noticed in the ini file , the paths to the autoexec files contain /storgage instead of /storage . Not sure if that matters.

Thanks,
Again

**Comment by dhwz** [comment]
The file is not read-only and we also have already an open issue.
