### ISSUE TITLE
Can 351ELEC be installed on a RG350M?

### ISSUE THREAD

**Issue by Tormentor667** [351ELEC/351ELEC#525]
Dear developers, sorry for derailing but I wasn’t sure where to post it. Is the 351ELEC installable on an Anbernic 350M device?

Thanks already in return!

**Comment by dhwz** [comment]
No, and please don't misuse our issues for support questions.

**Comment by Tormentor667** [comment]
Where can I ask something like that instead?

**Comment by Cebion** [comment]
350m is not supported and will never be supported. Sorry man

**Comment by SuperBadger77** [comment]
> Where can I ask something like that instead?

Discord.
