### ISSUE TITLE
Apple II emulator required

### ISSUE THREAD

**Issue by Praeambulum** [351ELEC/351ELEC#531]
## This is only for actual detailed feature requests for the system! For Support or if you want to discuss ideas visit us in our Discord
https://discord.gg/bmXtCt88Tz

### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Additional context

Applie II emulator would be a good choice for the next version, i think. The source/binary code for RG350 is as follows.

https://boards.dingoonity.org/gcw-development/(alpha)-kegs-for-gcw0-apple-iigs-emulator/

**Comment by szalik-rg351** [comment]
use template correctly, or join discord for suggestions
