### ISSUE TITLE
NGP and NGPC not launching

### ISSUE THREAD

**Issue by fry-guy** [351ELEC/351ELEC#535]
There seems to be some issue with Neo Geo Pocket and Neo Geo Pocket Color in the latest release... I am only able to play these games by entering RetroArch 64 bit under Tools, loading the game and then loading the Beetle NeoPop core. If I launch the game from the menu screen, it crashes into the "guru meditation" error.

I am confused since there are supposed to be two core options for these systems now... Beetle NeoPop and Race. However, I see no emulator options under "Per System Advanced Configuration" option under "Game Settings." Also, if I check the es_systems.cfg file in /usr/config/emulationstation, it appears that both cores are set as options for these systems and that beetle_ngp is set to the default. However, the games will not launch from the menu, which seems to conflict with my experience of being able successfully play the game by selecting that core directly from within retroarch. 

My only idea is that some setting is messed up somewhere and one or both of the cores is not being recognized by the default settings in emulation station, hence my inability to select either one as the default under the advanced settings, and it failing to launch from emulation station interface.

Thanks very much for the help.

**Comment by dhwz** [comment]
invalid issue
