### ISSUE TITLE
Advanced System Options is not setting the correct values for some Gameboy Colorization options.

### ISSUE THREAD

**Issue by Rolen47** [351ELEC/351ELEC#538]
### Describe the bug
The colorization option for "GBC" and "SGB" shouldn't be "internal" palette, Advanced System Options is setting them incorrectly.

### To Reproduce
1. Before choosing an original Gameboy game press the Select button and to go to Advanced System Options
2. Colorization
3. Select GBC or SGB.
4. Load game (in my test I used Pokemon Blue)
5. Check Colorization settings, they are wrong

Advanced System Options sets the following settings incorrectly:
GBC:
gambatte_gb_colorization = "internal"
gambatte_gb_internal_palette = "GBC"

SGB:
gambatte_gb_colorization = "internal"
gambatte_gb_internal_palette = "SGB"

### Expected behavior
This is the correct settings that Advanced System Options should be setting for these options:
GBC:
gambatte_gb_colorization = "GBC"
gambatte_gb_internal_palette = ""

SGB:
gambatte_gb_colorization = "SGB"
gambatte_gb_internal_palette = ""

The rest of the colorization options appear to be functioning correctly because they are "Internal" colorization.

### Device (please complete the following information):
RG351V with 351ELEC 20210603

**Comment by dhwz** [comment]
@konsumschaf can you please check that

**Comment by konsumschaf** [comment]
Start working on this ...

**Comment by konsumschaf** [comment]
Fixed in https://github.com/351ELEC/351ELEC/pull/556
