### ISSUE TITLE
README.md could use a section about how 351ELEC is different and why one might want to use it

### ISSUE THREAD

**Issue by tibbe** [351ELEC/351ELEC#549]
Basically what the title says. As a (potential) new user it's unclear after landing on GitHub why one might want to use this firmware. Does it support more platforms? Is it faster? Is its UI better? How does it differ compared to X?

**Comment by dhwz** [comment]
misuse of our issues section

**Comment by pkegg** [comment]
Just to elaborate on what dhwz said, the suggest is valid but in the wrong place.  The place to discuss things like that is on our discord server.  Issues are only for reproducible bugs with 351ELEC, etc.
