### ISSUE TITLE
Restarting N64 games crashes the game/RetroArch permanently

### ISSUE THREAD

**Issue by ameliebou** [351ELEC/351ELEC#551]
### Describe the bug
If I try to restart any N64 game in RetroArch it shuts down and gives the following error message: "System Failure. Check Log Files for more information. Guru Meditation #68B329DA9893E3409". Afterwards when 351ELEC is restarted, it's not possible to restart the game again (it will always lead to the same error message). The only thing to make the game work again is to rename the game file (so I guess that something in the RetroArch settings for this game is damaged).

### To Reproduce
1. Start any N64 game
2. Open RetroArch
3. Choose "Restart"
4. Game crashes

### Expected behavior
Game should restart without getting damaged.

### Device
Happens both on the RG351P and the RG351V.
Both are running with 351ELEC - 20210603 Crazy Hedgehog (Hotfix3). Since it's the first firmware I installed on both systems I can't say if it was also a problem in earlier versions.

**Comment by dhwz** [comment]
Disable autosave
