### ISSUE TITLE
Weapon Menu in the original Syphon Filter (PS1)

### ISSUE THREAD

**Issue by abelogan** [351ELEC/351ELEC#568]
When I try to play Syphon Filter, I hold Select and press R1 or L1, but it just saves or loads a game state, respectively.  So, I remap wsave state and load state to R3 and L3, but still. when I hold Select and press L1 or R1. no weapon menu comes up.  Can[t play the game if you can't access your flashlight or viral  scanner! :(

**Comment by Rolen47** [comment]
You can change your "Hotkey Enable" to something else instead of select. I have mine set to R3.
