### ISSUE TITLE
OpenBOR Games Screen Resolution Issue

### ISSUE THREAD

**Issue by vdincman** [351ELEC/351ELEC#582]
OpenBOR emulator doesn't have a full screen option on both 351P and 351V.  Games don't fit the screen on both handhelds and look very blurry, whatever the aspect ratio is, with both linear and bilinear filtering options. Anbernic's Stock Firmware has the Fullscreen option, and it is looking much better, especially on the 351V screen.

**Comment by DieHardMan5x** [comment]
Thats because an PSP emulator is used. The commit from back then should be reverted, except for the controls, the old OpenBor worked and looked good. Even He-Man ran on it, which is not the case now.

**Comment by dhwz** [comment]
We will switch back to OpenBOR in a later release.
