### ISSUE TITLE
Button mapping using Retrorun on N64

### ISSUE THREAD

**Issue by borrrris** [351ELEC/351ELEC#583]
### Describe the bug
The shoulder buttons are on the R2 and R1 buttons, and the "c" buttons are not configured..

### To Reproduce
1. Start any game (example Banjo-Kazooe) using Retrorun Parallel n64 gln64
2. Move the right analog stick to move the camera.
3. Press any button to move the camera.
4. The camera does not move because the "c" buttons are not configured..

### Expected behavior
N64 / RG351p:
L / L1
R / R1
Analog stick / left stick
C buttons / right stick
Z / L2

### Device 
 - 351ELEC-RG351P.aarch64-20210603

**Comment by dhwz** [comment]
This is not a bug we currently have no button mapping in retrorun. The buttons are automatically assigned by the used core.
