### ISSUE TITLE
Brightness hotkey on RG351V doesn't work

### ISSUE THREAD

**Issue by onibirdo** [351ELEC/351ELEC#595]
**Device**
RG351V

**351ELEC version**
351ELEC - 20210603 Crazy Hedgehog (Hotfix3)

**Issue**
Either there is no hotkey to change the brightness on the RG351V, or the hotkey doesn't work.
I tried:

- L3 + D-pad up/down
- L3 + R1/L1
- Function key + D-pad up/down
- Function key + R1/L1
- L3 + volume button up/down
- Function key + volume button up/down

None of the above work. The brightness doesn't change. I've verified it in the EmulationStation UI.

**Comment by Cebion** [comment]
The hotkey does not work in Emulationstation

**Comment by nojohnso** [comment]
Doesn't work in-game either. I've tried all of the above hotkey combinations.
