### ISSUE TITLE
PCEngine CD issue with syscard3.pce

### ISSUE THREAD

**Issue by pzirnik** [351ELEC/351ELEC#596]
When i try to use PCEngine CD .chd files it does not work. After some try&error i discovered i need to place the syscard3.pce into the same folder where the .chd file is (like ~/roms/pcenginecd/) to make it work. If the syscard3.pce is in ~/roms/bios/ folder it does not work. As i have no experience til now, i can´t figure out if this is a 351elec port issue or a global issue.

**Comment by dhwz** [comment]
Then you are doing something wrong as it works perfectly fine for me.
