### ISSUE TITLE
Software Failur on SNES and Sega Genesis

### ISSUE THREAD

**Issue by KnallerGer** [351ELEC/351ELEC#599]
when I start a SNES or a Sega Genesis game the error message appears as shown in the picture.  Playstation 1 games run flawlessly.  until 2 days ago the same SNES games were still running without errors.

1. Go to SNES Games
2. Click on any Game
3. See error

![PXL_20210826_204757336](https://user-images.githubusercontent.com/89671071/131201588-b205c299-7b35-4b62-8927-72755d30cab8.jpg)

I hope someone can help me and thank you in advance.

**Comment by joseMartinezDev** [comment]
Why was this issue closed? I'm having this same problem with some roms. Is there any way to fix it?

**Comment by dhwz** [comment]
Issues are not intended for support. "Bug report, only open after discord report!"
Join Discord for support, as this is no issue but a user misuse.
