### ISSUE TITLE
Update dosbox pure to 0.16 (fixes running Windows 3.1 from a dosz file among other issues)

### ISSUE THREAD

**Issue by nl255** [351ELEC/351ELEC#605]
There is a new release of dosbox pure (0.16) that has fixes to dosz support.  Specifically : "The problem specifically was opening a file for writing from the ZIP (which causes it to be copied out of the ZIP into the save file on the first write operation) and then seeking past the end of the file (to write there and have the data between filled with zero bytes). It's not very common to do that but it is supported by the standard so there are programs here and there that rely on that working."

Upgrading to 0.16 will also make it possible to use .dosz files larger than 4GB and some other bugfixes.

**Comment by dhwz** [comment]
No need to open an issue we update cores on each release.
