### ISSUE TITLE
Getting a Segmentation Fault when trying to launch any NEC PC-98 roms

### ISSUE THREAD

**Issue by mikepruett3** [351ELEC/351ELEC#688]
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

Getting a red error message (Software Failure) when trying to launch any NEC PC98 rom using the np2kai core. When I look at the exec.log under /tmp/logs, I see the folowing

Loading np2kai.cfg from /storage/roms/bios/np2kai/np2kai.cfgSaving np2kai.cfg to /storage/roms/bios/np2kai/np2kai.cfgSegmentation fault

I was able to launch a few PC98 roms before this, but for some reason (even after I factory reset) I still cannot run any games

I have also verified my BIOS files are correct, and match the MD5 sums in the wiki.

Running version 20210603

**Comment by jordanaycamara** [comment]
I'm getting the same problem on mine. Some PC98 games ran fine the first time, and then when I went and relaunched them, I get  a segmentation fault error

**Comment by dhwz** [comment]
Disable autosave for pc98

**Comment by mikepruett3** [comment]
> Disable autosave for pc98

That was the fix!!! Thank you!!!
