### ISSUE TITLE
[Request] Can you bump the mGBA core?

### ISSUE THREAD

**Issue by vanfanel** [351ELEC/351ELEC#698]
Current mGBA core version has audio buffering problems we have been watching for many years, but now they have been finally fixed:

https://github.com/libretro/mgba/issues/109

This allows to have the same low-latency settings with this core that we use with other cores.
I know I asked this on Discord already, but I asked it on the wrong place (BETA reports) and I believe this is the right one.

**Comment by dhwz** [comment]
seriously stop asking!
