### ISSUE TITLE
EmulationStation has trouble with some custom shader presets

### ISSUE THREAD

**Issue by seriouslyunderappreciated** [351ELEC/351ELEC#699]
### Describe the bug
2xBR+VBA-Color custom shader loads fine when manually selected within retroarch, but if chosen from emulationstation it boots games with a black screen. After accessing the shaders menu on retroarch once the game is booted and the image is black, you can see that the shader pipeline/parameters are all correct, and hitting "apply" will bring the image back with the expected shader combination.

### To Reproduce
-Go to either global, per system configuration, or advanced game options for shaders in emulationstation
-Choose the custom preset attached at the end of this report
-Launch the game (I made the preset for GBA, and the games are being launch with the mGBA core, though I doubt that matters much)

or make the preset yourself:
-In retroarch, go to shaders
-Load 2xBR multipass
-You should now have 2 passes preconfigured, add a third pass of the VBA-Color shader
-Leave parameters as they are, save this preset, test it immediately if you wish
-Go to emulationstation, select your new custom preset
-Launch a game with it, it will have a black image.

### Expected behavior
The screen shouldn't be black, you shouldn't have to open the shaders menu in RA and apply preexisting shaders for the image to appear again.

### Screenshots
https://youtu.be/oPILPBFiunY

### Device (please complete the following information):
351ELEC - 20210603 Crazy Hedgehog (Hotfix3)
Also tested on beta-20211102_2015, bug still present.

### Additional context
Copy of shader preset attached.

[darkxbr.zip](https://github.com/351ELEC/351ELEC/files/7470490/darkxbr.zip)
.

**Comment by dhwz** [comment]
As I've already explained yesterday there is nothing we can do, thats a RetroArch issue.
