### ISSUE TITLE
PSP buttons not mapped correctly for 351P

### ISSUE THREAD

**Issue by Ewar72** [351ELEC/351ELEC#729]
## This is only for actual bugs that can be reproduced on multiple systems!  ##
 For Support visit us in our Discord
https://discord.gg/bmXtCt88Tz

### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Describe the bug
Button mapping for the stand alone PSP Emulator PPSSPPSDL are not correct on the 351P version. Nov 22 2021 Release version

### To Reproduce
Try using the PPSSPPSDL Emulator - buttons are not mapped.

### Expected behavior
Correct button mapping

### Device (please complete the following information):
 351P version. Nov 22 2021 Release version

**Comment by dhwz** [comment]
Delete your ppsspp.ini and controls.ini from GAMES/gamedata/ppsspp folder
