### ISSUE TITLE
Mupen64PlusSA: M64P Rice wrong button mapping

### ISSUE THREAD

**Issue by glaucon1984** [351ELEC/351ELEC#738]
### Describe the bug
Mupen64PlusSA: M64P Rice emulator has the wrong button mapping but there is no way to re-configure it.
L2 is not mapped to Z
Right Stick is not mapped to C buttons

### To Reproduce
Go to Nintendo 64 list of games, press "select" -> Emulator -> Advanced System Options
Select Mupen64PlusSA: M64P Rice
Run Mario 64
As soon as you can control Mario:
- L1 and L2 don't perform any action, Mario should duck, but he doesn't.
- Right stick cannot move the camera right or left, up or down.

### Expected behavior
The right stick should act as the C up/down/left/right buttons. Even when the game restrict camera movement, there should be a sound to indicate that the movement is restricted, there is no sound. "A" button performs the action "C  down", R2 does "C right" and X "C left", for reference.
L2 should act as the Z button. Mario should duck.

### Device (please complete the following information):
Anbernic RG351P
351ELEC - 20211122 Pineapple Forest

### Additional context
There doesn't seem to be a way to reconfigure the buttons, unlike with Retroarch cores.

I don't own any N64 game that uses the L button, but L1 on the RG351 might need to be mapped to L on the N64 controller.

**Comment by dhwz** [comment]
https://351elec.de/System-N64
