### ISSUE TITLE
[Pineapple Forest] Mupen64 retroarch cores don't work, crashing to menu after ROM load

### ISSUE THREAD

**Issue by freq-mod** [351ELEC/351ELEC#741]
### Describe the bug
As stated in title - both M64P and M64P-Next retroarch cores are completely dead, they crash to main menu the moment emulation starts. The issue happens with unzipped ROMs, of both .z64 and .n64 extensions. The rest of emulators have no problems running both games.

### To Reproduce
1. Select unzipped Nintendo 64 game
2. Go to "Advanced game options"
3. Select Retroarch/Mupen64[...] core
4. Run the game

### Expected behavior
idk, it should work in some capacity? ParaLLEi cores work, with severe slowdown and graphical glitches, but no crashes.

### Device (please complete the following information):
351ELEC, Pineapple Forest release, Anbernic RG351P

Also: when running the 32-bit retroarch directly from the "tools" sub-menu, only Mupen64Plus-Next core is present. Trying to load any ROM with it fails with "failed to open libretro core". With 64-bit retroarch, no such error is displayed, but it just crashes to menu.

**Comment by dhwz** [comment]
https://351elec.de/System-N64
