### ISSUE TITLE
[351V] WIFI - strange bevaviour

### ISSUE THREAD

**Issue by MeCias** [351ELEC/351ELEC#743]
Hi,

I noticed some strange behaviour with my 351V and a fresh installed Pineapple Forest.  Just wanted to ask whether that is just a behaviour on my device or somebody else is noticing that as well.

I did a setup with my WIFI credentials and that works as expected as soon I am not using a [hidden](https://github.com/351ELEC/351ELEC/discussions/689) WIFI Network.

Usually I switch the WIFI off on my device just to hope for a little more battery life. I toggle the switch within the settings.
What I've noticed now was, that as soon I toggle the WIFI off and restart the device on some point WIFI is active and working doesn't matter whether the toggle is off within the settings or the WIFI is hidden.

Quite not sure why that is the case, but maybe somebody can confirm that behaviour or it is maybe just an issue with my device.

Thanks in advance.

**Comment by dhwz** [comment]
Don't misuse our issues section for your personal support questions, come to our Discord Server for support.
https://discord.gg/bmXtCt88Tz
