### ISSUE TITLE
IF RG351MP is connected to Network "XY" , load savegame from network share otherwise use local savegame

### ISSUE THREAD

**Issue by peterpan192** [351ELEC/351ELEC#785]
Hey,
since Recalbox on my Raspberry pi loads save games from my nas, I was interested if it is possible to tell 351ELEC to do so as well but only if it's connected to a particular Network (Wifi@home). If it's connected to another Wifi or not using wifi at all, it should use the locally stored savegames. 
Is there any way to put that into an extension file?

**Comment by dhwz** [comment]
I don't think this is possible.
Please don't use the issues section for support questions and ask such questions on Discord.
