### ISSUE TITLE
Delete rom file at Game Options (SELECT Button)

### ISSUE THREAD

**Issue by xmassound** [351ELEC/351ELEC#79]
### Getting started
It's nice to have DELETE file option while browsing roms per Platform.

### Describe the solution you'd like
Easy way would be to select (highlight) current rom and press SELECT button to show options.
Above Edit metadata, "DELETE FILE" menu will delete selected rom file.

### Describe alternatives you've considered
Toggle confirmation popup (like trashbin in windows 10) would be nice so that you can easily delete roms you
don't want.
![IMG_1708](https://user-images.githubusercontent.com/12112315/103505030-07a9a880-4e0e-11eb-81eb-1d764d92bd75.jpg)
![IMG_1709](https://user-images.githubusercontent.com/12112315/103505033-08dad580-4e0e-11eb-9309-0a9c42fd0364.jpg)

**Comment by overburner** [comment]
There are "DELETE" button inside the "EDIT THIS GAME'S METADATA" already 😄

**Comment by fewtarius** [comment]
I can't guarantee that we'll add it, but I'll look into it.

**Comment by fewtarius** [comment]
I started looking into this and decided that since there's a delete option on the metadata page we won't add it.
